package org.openmrs.module.registrationcore.api.errorhandling;

/**
 * This service allows a bean to handle the errors generated by the registration core. This allows functionality such as
 * the retrying of failed MPI interactions due to lack of connectivity.
 */
public interface ErrorHandlingService {

    void handle(String messageBody, String destination, boolean failure, String failureReason);
}
